services:
  backend:
    build: .
    ports:
      - "3001:3001"
    command: npm run dev_docker
    volumes:
      - "./src:/app/src:ro"
    
  db: 
    image: postgres
    ports:
      - "5432:5432"